<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Celeste.Mod.MicroblocksQolUtils</RootNamespace>
    <AssemblyName>MicroblocksQolUtils</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CelesteRoot>$(MSBuildThisFileDirectory)..\..\..\vendor\celeste-game</CelesteRoot>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Celeste"><HintPath>$(CelesteRoot)\Celeste.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="FNA"><HintPath>$(CelesteRoot)\FNA.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MMHOOK_Celeste"><HintPath>$(CelesteRoot)\MMHOOK_Celeste.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Mono.Cecil"><HintPath>$(CelesteRoot)\Mono.Cecil.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MonoMod.RuntimeDetour"><HintPath>$(CelesteRoot)\MonoMod.RuntimeDetour.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MonoMod.Utils"><HintPath>$(CelesteRoot)\MonoMod.Utils.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Drawing.Common"><HintPath>$(CelesteRoot)\System.Drawing.Common.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
