#!/usr/bin/env node
// Render a `tas_fidelity` JSON report as a readable Markdown document.
//
//   node tools/tas-fidelity/render-report.mjs <report.json> <out.md>

import fs from 'node:fs';
import path from 'node:path';

const [reportPath, outPath] = process.argv.slice(2);
if (!reportPath || !outPath) {
  console.error('usage: render-report.mjs <report.json> <out.md>');
  process.exit(2);
}

const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
const totals = report.totals ?? {};

const num = (value) => (typeof value === 'number' ? value.toLocaleString('en-US') : '0');
const pct = (part, whole) => (whole > 0 ? `${((100 * part) / whole).toFixed(2)}%` : 'n/a');
const code = (value) => (value === null || value === undefined ? '`–`' : `\`${value}\``);
const row = (cells) => `| ${cells.join(' | ')} |`;

function table(header, rows) {
  if (rows.length === 0) return '_none_\n';
  return [row(header), row(header.map(() => '---')), ...rows.map(row)].join('\n') + '\n';
}

const lines = [];
lines.push('# celeste-physics vs real-game Celeste TAS — frame-level fidelity report');
lines.push('');
lines.push(`* trace: \`${report.trace}\``);
lines.push(`* maps: \`${report.mapsDir}\``);
lines.push(`* generated by: \`${report.generatedBy}\``);
lines.push('');
lines.push('## Headline totals');
lines.push('');
lines.push(
  table(
    ['metric', 'value'],
    [
      ['JSONL rows read', num(totals.records)],
      ['rows with `scene == "Level"`', num(totals.levelRecords)],
      ['non-level rows (skipped)', num(totals.nonLevelRecords)],
      ['row parse errors', num(totals.parseErrors)],
      ['segments (maximal same-`(sid,mode,room)` runs)', num(totals.segments)],
      ['segments simulated', num(totals.simulatedSegments)],
      ['segments skipped (below `--min-frames` / room filter)', num(totals.skipped)],
      ['replayed frames', num(totals.totalFrames)],
      [
        'frames matching (`exactFrames`)',
        `${num(totals.exactFrames)} (${pct(totals.exactFrames, totals.totalFrames)} of replayed frames)`,
      ],
      ['frames where `Player.Update` did not run (skipped, not compared)', num(totals.stalledFrames)],
    ],
  ),
);
lines.push('');
lines.push('### Segment status');
lines.push('');
lines.push(
  table(
    ['status', 'segments'],
    [
      ['`ok` — every replayed frame matched', num(totals.ok)],
      ['`mismatch` — first differing frame recorded', num(totals.mismatch)],
      ['`unsupported` — `SimulationError::UnsupportedState`', num(totals.unsupported)],
      ['`init_error` — `Simulator::new` rejected the restored snapshot', num(totals.initError)],
      ['`map_error` — area `.bin` / room could not be resolved', num(totals.mapError)],
      ['`state_map_error` — unknown `state` name (never a panic)', num(totals.stateMapError)],
      ['`no_live_window` — no replayable `Player.Update` window', num(totals.noLiveWindow)],
      ['`sim_error` — other `SimulationError`', num(totals.simError)],
    ],
  ),
);
if (totals.truncated) {
  lines.push('');
  lines.push('> `--limit-segments` reached: the scan stopped early, so the row totals above are partial.');
}
lines.push('');

const comparison = report.comparison ?? {};
lines.push('## How frames are compared');
lines.push('');
lines.push(`* tolerance \`${comparison.tolerance}\` on \`pos\`, \`speed\`, \`stamina\`; exact equality on \`${(comparison.exact ?? []).join('`, `')}\`.`);
lines.push(`* position source: ${comparison.positionSource ?? 'n/a'}`);
lines.push(`* frame delta time: ${comparison.frameDeltaTime ?? 'n/a'}`);
lines.push(`* skipped frames: ${comparison.stalledFrames ?? 'n/a'}`);
const unavailable = comparison.unavailable ?? {};
if (Object.keys(unavailable).length > 0) {
  lines.push('');
  lines.push('Ground-truth values that the trace cannot supply (never compared):');
  lines.push('');
  lines.push(table(['field', 'why'], Object.entries(unavailable).map(([k, v]) => [code(k), v])));
}
lines.push('');

// ---------------------------------------------------------------------------
// Rooms, worst first.
// ---------------------------------------------------------------------------
const rooms = Object.entries(report.rooms ?? {}).map(([key, stat]) => ({ key, ...stat }));
const worstFirst = (list) =>
  [...list].sort(
    (a, b) =>
      a.medianExactPrefix - b.medianExactPrefix ||
      a.minExactPrefix - b.minExactPrefix ||
      b.frames - a.frames ||
      a.key.localeCompare(b.key),
  );

const renderRooms = (list, limit) =>
  table(
    ['room (`sid|mode|room`)', 'segments', 'frames', 'ok', 'mismatch', 'unsupported', 'median exactPrefix', 'min', 'max'],
    worstFirst(list)
      .slice(0, limit)
      .map((stat) => [
        code(stat.key),
        num(stat.segments),
        num(stat.frames),
        num(stat.ok),
        num(stat.mismatch),
        num(stat.unsupported),
        num(stat.medianExactPrefix),
        num(stat.minExactPrefix),
        num(stat.maxExactPrefix),
      ]),
  );

lines.push('## Rooms with the smallest `exactPrefixFrames` (worst offenders first)');
lines.push('');
lines.push('Ranked by median `exactPrefixFrames`, then by the minimum.');
lines.push('');
lines.push(renderRooms(rooms, 40));
lines.push('');
lines.push('### Same ranking, restricted to rooms with at least 100 replayed frames');
lines.push('');
lines.push(renderRooms(rooms.filter((room) => room.frames >= 100), 25));
lines.push('');

// ---------------------------------------------------------------------------
// Unsupported states.
// ---------------------------------------------------------------------------
const unsupported = Object.entries(report.byUnsupportedState ?? {});
lines.push('## Unsupported player states');
lines.push('');
lines.push(
  table(
    ['state', 'segments stopped here', 'replayed frames before the failure', 'rows whose state name equals it'],
    unsupported
      .sort((a, b) => b[1].segments - a[1].segments || a[0].localeCompare(b[0]))
      .map(([state, stat]) => [
        code(state),
        num(stat.segments),
        num(stat.frames),
        num(stat.rowsInState ?? 0),
      ]),
  ),
);
lines.push('');

// ---------------------------------------------------------------------------
// First mismatches.
// ---------------------------------------------------------------------------
const mismatches = (report.segments ?? []).filter((segment) => segment.firstMismatch);
const reasonCounts = new Map();
for (const segment of mismatches) {
  for (const reason of segment.firstMismatch.reasons) {
    reasonCounts.set(reason, (reasonCounts.get(reason) ?? 0) + 1);
  }
}
lines.push('## First-mismatch reason histogram');
lines.push('');
lines.push(
  table(
    ['reason', 'segments whose FIRST mismatch includes it'],
    [...reasonCounts.entries()]
      .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
      .map(([reason, count]) => [code(reason), num(count)]),
  ),
);
lines.push('');

lines.push(`## First ${Math.min(30, mismatches.length)} mismatch segments`);
lines.push('');
for (const segment of mismatches.slice(0, 30)) {
  const mismatch = segment.firstMismatch;
  lines.push(
    `### \`${segment.sid}|${segment.mode}|${segment.room}\` @ row ${segment.startRow} (tas frame ${segment.startFrame})`,
  );
  lines.push('');
  lines.push(
    `* status \`${segment.status}\`, exact prefix \`${segment.exactPrefixFrames}\` of \`${segment.frames}\` replayed frames (${segment.records} trace rows; \`${segment.leadingSkippedFrames}\` leading and \`${segment.stalledFrames}\` stalled frames skipped)`,
  );
  lines.push(`* first mismatch at frame offset \`${mismatch.offset}\`: **${mismatch.reasons.join(', ')}**`);
  const rust = mismatch.rust ?? {};
  const game = mismatch.game ?? {};
  lines.push('');
  lines.push(
    table(
      ['field', 'celeste-physics', 'real game (trace)'],
      [
        ['row', code('–'), code(game.row)],
        ['pos', code(JSON.stringify(rust.pos)), code(JSON.stringify(game.pos))],
        ['speed', code(JSON.stringify(rust.speed)), code(JSON.stringify(game.speed))],
        ['state', code(rust.state), code(game.state)],
        ['facing', code(rust.facing), code(game.facing)],
        ['dashes', code(rust.dashes), code(game.dashes)],
        ['stamina', code(rust.stamina), code(game.stamina)],
        ['onGround', code(rust.onGround), code(game.onGround)],
        ['playerOnGround (source-private)', code(rust.playerOnGround), code('–')],
        ['dead', code(rust.dead), code(game.dead)],
        ['ducking', code(rust.ducking), code('not exported')],
        ['stateTimer', code(rust.stateTimer), code('not exported')],
        ['movementRemainder', code(JSON.stringify(rust.movementRemainder)), code('not exported')],
        ['varJumpTimer', code(rust.varJumpTimer), code('–')],
        ['dashCooldownTimer', code(rust.dashCooldownTimer), code('–')],
        ['wallSlideTimer', code(rust.wallSlideTimer), code('–')],
      ],
    ),
  );
  if (segment.remainderProbe) {
    const probe = segment.remainderProbe;
    lines.push('');
    lines.push(
      `* movement-remainder probe: baseline \`${probe.baselineExactPrefixFrames}\` frames; ` +
        probe.axes
          .map((axis) => `\`${axis.axis}=${axis.bestValue}\` → \`${axis.bestExactPrefixFrames}\``)
          .join(', ') +
        (probe.best2d
          ? `; joint \`(${probe.best2d.x}, ${probe.best2d.y})\` → \`${probe.best2d.exactPrefixFrames}\``
          : ''),
    );
  }
  lines.push('');
}

const fieldMap = report.fieldMap;
if (fieldMap) {
  lines.push('## `PlayerSnapshot` field coverage');
  lines.push('');
  lines.push(
    `Declared fields \`${fieldMap.audit.declaredFields}\`: restored from a trace key \`${fieldMap.audit.restored}\`, derived by the harness \`${fieldMap.audit.derived}\`, unrestorable \`${fieldMap.audit.unrestored}\`. ` +
      `Missing from table: \`${JSON.stringify(fieldMap.audit.missing)}\`; stale table entries: \`${JSON.stringify(fieldMap.audit.stale)}\`.`,
  );
  lines.push('');
  lines.push('### Restored from the trace');
  lines.push('');
  lines.push('| PlayerSnapshot field | type | trace key |');
  lines.push('| --- | --- | --- |');
  for (const entry of fieldMap.restored) {
    lines.push(`| \`${entry.field}\` | \`${entry.kind}\` | \`${entry.source}\` |`);
  }
  lines.push('');
  lines.push('### Derived by the harness');
  lines.push('');
  lines.push('| PlayerSnapshot field | how |');
  lines.push('| --- | --- |');
  for (const entry of fieldMap.derived) {
    lines.push(`| \`${entry.field}\` | ${entry.source} |`);
  }
  lines.push('');
  lines.push('### No ground-truth source');
  lines.push('');
  lines.push('| PlayerSnapshot field | why |');
  lines.push('| --- | --- |');
  for (const entry of [...fieldMap.unrestored].sort((a, b) => a.field.localeCompare(b.field))) {
    lines.push(`| \`${entry.field}\` | ${entry.source} |`);
  }
  lines.push('');
}

fs.mkdirSync(path.dirname(path.resolve(outPath)), { recursive: true });
fs.writeFileSync(outPath, lines.join('\n'));
console.log(`wrote ${outPath} (${lines.length} lines)`);
