import celesteRooms from "../public/assets/celeste/room-themes.json";
import strawberryJamRooms from "../public/assets/strawberry-jam/room-themes.json";
import cny2024Rooms from "../public/assets/cny2024/room-themes.json";
import type { VisualTheme, VisualThemeCollectionId, VisualThemeLayer } from "./visualThemes";
import type { TileSetDef } from "./tileRules";

/**
 * One switchable theme per map, generated by scripts/extract-mod-themes.mjs
 * from the mod pack (tileset + autotiler rules, spike type, spinner, parallax
 * background layers). Map names come from each mod's Simplified Chinese dialog.
 */

interface RoomThemeData {
  id: string;
  label: string;
  mapFile: string;
  room: string;
  rooms: readonly string[];
  roomCount: number;
  tileset: string | null;
  tileRules: readonly (readonly [string, readonly [number, number]])[] | null;
  centerTile: readonly [number, number] | null;
  paddedTile: readonly [number, number] | null;
  tileScan: readonly [number, number] | null;
  tileIgnores?: string;
  tilesets?: Record<string, TileSetDef>;
  spike: string;
  spinner: { foreground: string; background: string } | null;
  background: string;
  atlas?: string;
  preview?: string;
  layers: readonly {
    key: string;
    scrollX: number;
    scrollY: number;
    loopX: boolean;
    loopY: boolean;
    speedX: number;
    speedY: number;
    opacity: number;
  }[];
}

function toTheme(
  room: RoomThemeData,
  collection: VisualThemeCollectionId,
): VisualTheme {
  return {
    id: `room:${room.id}`,
    label: room.label,
    chapter: room.mapFile,
    collection,
    tileset: room.tileset ?? "tilesets/dirt",
    ...(room.tileRules ? { tileRules: room.tileRules } : {}),
    ...(room.centerTile ? { centerTile: room.centerTile } : {}),
    ...(room.paddedTile ? { paddedTile: room.paddedTile } : {}),
    ...(room.tileScan ? { tileScan: room.tileScan } : {}),
    ...(room.tileIgnores ? { tileIgnores: room.tileIgnores } : {}),
    ...(room.tilesets ? { tilesets: room.tilesets } : {}),
    spike: room.spike,
    spinner: room.spinner ?? {
      foreground: "danger/crystal/fg_blue",
      background: "danger/crystal/bg_blue",
    },
    background: room.background,
    ...(room.atlas ? { atlasUrl: room.atlas } : {}),
    ...(room.preview ? { previewUrl: room.preview } : {}),
    layers: room.layers.map(
      (layer): VisualThemeLayer => ({
        key: layer.key,
        opacity: layer.opacity,
        scrollX: layer.scrollX,
        scrollY: layer.scrollY,
        loopX: layer.loopX,
        loopY: layer.loopY,
        speedX: layer.speedX,
        speedY: layer.speedY,
      }),
    ),
  };
}

export const ROOM_THEMES: readonly VisualTheme[] = [
  ...(celesteRooms.rooms as unknown as readonly RoomThemeData[]).map((room) =>
    toTheme(room, "celeste-rooms"),
  ),
  ...(strawberryJamRooms.rooms as unknown as readonly RoomThemeData[]).map((room) =>
    toTheme(room, "strawberry-jam-rooms"),
  ),
  ...(cny2024Rooms.rooms as unknown as readonly RoomThemeData[]).map((room) =>
    toTheme(room, "cny2024-rooms"),
  ),
];
